name: Build & Publish

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build solution
        run: dotnet build -c Release
      - name: Publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Clipper/Clipper.csproj # Relative to repository root
          VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
          TAG_COMMIT: true # Flag to enable / disable git tagging
          TAG_FORMAT: v* # Format of the git tag, [*] gets replaced with version
          INCLUDE_SYMBOLS: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key