name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        run: dotnet pack clipper_library.csproj
               -c Release
               --include-source
               --include-symbols